### ISSUE TITLE
Addressbar displays "Go to a website" when clicked on window.open() javascript

### ISSUE THREAD

**Issue by htmltiger** [nedwidek/firefox-gmail-manager-ng#19]
screenshot 
http://i.imgur.com/t557C.png

When clicked on the first link on this page
http://www.javascript-coder.com/files/window-popup/javascript-window-open-example1.html

it should display the address of the site where is only displays default "Go to a website" text.

Using firefox 10.0.1 and disabled all the addons and just by enabling this addon it causes this issue.

please check it.

Thanks.

**Comment by nedwidek** [comment]
My guess would be that this is in the handling of mailto: links. I'm investigating, but I will definitely push back milestone .6.5.3 to get this one in.

**Comment by nedwidek** [comment]
Interesting issue. Might need to write this up as a Firefox bug, but I have a work around.

var windowContent = window.document.getElementById("content"); // <--- This was the problem.
windowContent.addEventListener("click", gmanager_ContentAreaClick, false);

But rewriting it as this works:
content.addEventListener("click", gmanager_ContentAreaClick, false);

Fixed in 0.6.5.3

**Comment by htmltiger** [comment]
Just tested and it works fine.

Thanks for everything.
